name: deploy-ui-to-mainnet
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      maintenance:
        type: boolean
        description: Deploy in maintenance mode?
        required: true
        default: false

jobs:
  deploy-ui-to-mainnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: vercel-action-mainnet
        with:
          scope: ${{ secrets.AXELAR_TEAM_ID_VERCEL }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_BRIDGE_MAINNET_PROJECT_ID }}
          vercel-args: "--prod --build-env REACT_APP_UNDER_MAINTENANCE=${{github.event.inputs.maintenance}}"
          alias-domains: |
            satellite.axelar.network
            axelar-satellite-mainnet.vercel.app
        env:
          REACT_APP_UNDER_MAINTENANCE: ${{github.event.inputs.maintenance}}
