name: deploy-ui-to-mainnet
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy-ui-to-devnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: vercel-action-mainnet
        with:
          scope: ${{ secrets.AXELAR_TEAM_ID_VERCEL }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_BRIDGE_MAINNET_PROJECT_ID }}
          vercel-args: '--prod'
          alias-domains: |
            axelar-bridge-mainnet.vercel.app